config:
  backup: true
  banner: true
  check_version: true
  compare_workdir: true
  create: true
  dotpath: ~/.local/dotfiles
  keepdot: true
  link_dotfile_default: absolute
  link_on_import: absolute
  longkey: true
  showdiff: true
dotfiles:
  f_bashrc:
    src: .bashrc
    dst: ~/.bashrc
  f_default-python-packages:
    src: .default-python-packages
    dst: ~/.default-python-packages
  f_gitconfig:
    src: .gitconfig
    dst: ~/.gitconfig
  f_tool-versions:
    src: .tool-versions
    dst: ~/.tool-versions
  f_gnupg_gpg-agent.conf:
    src: .gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
  f_ssh_config:
    src: .ssh/config
    dst: ~/.ssh/config
profiles:
  KLAUSEWDEV-WS:
    dotfiles:
    - f_bashrc
    - f_default-python-packages
    - f_gitconfig
    - f_tool-versions
    - f_gnupg_gpg-agent.conf
    - f_ssh_config
