config:
  backup: true
  banner: true
  check_version: true
  compare_workdir: true
  create: true
  dotpath: ~/.local/dotfiles
  keepdot: true
  link_dotfile_default: absolute
  link_on_import: absolute
  longkey: true
  showdiff: true
dotfiles:
  f_bashrc:
    src: .bashrc
    dst: ~/.bashrc
  f_config_gh_config.yml:
    src: .config/gh/config.yml
    dst: ~/.config/gh/config.yml
    chmod: '600'
  f_config_jgit_config:
    src: .config/jgit/config
    dst: ~/.config/jgit/config
  f_config_yay_config.json:
    src: .config/yay/config.json
    dst: ~/.config/yay/config.json
  f_default-python-packages:
    src: .default-python-packages
    dst: ~/.default-python-packages
  f_gitconfig:
    src: .gitconfig
    dst: ~/.gitconfig
  f_gnupg_gpg-agent.conf:
    src: .gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
  f_lem_init.lisp:
    src: .lem/init.lisp
    dst: ~/.lem/init.lisp
  f_sbclrc:
    src: .sbclrc
    dst: ~/.sbclrc
  f_ssh_config:
    src: .ssh/config
    dst: ~/.ssh/config
  f_tool-versions:
    src: .tool-versions
    dst: ~/.tool-versions
  d_config_jetbrains:
    src: .config/JetBrains
    dst: ~/.config/JetBrains
profiles:
  KLAUSEWDEV-WS:
    dotfiles:
    - f_bashrc
    - f_config_gh_config.yml
    - f_config_jgit_config
    - f_config_yay_config.json
    - f_default-python-packages
    - f_gitconfig
    - f_gnupg_gpg-agent.conf
    - f_lem_init.lisp
    - f_sbclrc
    - f_ssh_config
    - f_tool-versions
    - d_config_jetbrains
